// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzDr_XflAEIQuTEiMSgqhEPXrWwCW7tPg',
    appId: '1:607004529726:web:3ae046d556117733efed6f',
    messagingSenderId: '607004529726',
    projectId: 'cinemora-63661',
    authDomain: 'cinemora-63661.firebaseapp.com',
    storageBucket: 'cinemora-63661.firebasestorage.app',
    measurementId: 'G-RF61SBKX8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOKWQNFOtcQZSSQgMk-PPHMtVw5WW07vo',
    appId: '1:607004529726:android:4fae4078963ff513efed6f',
    messagingSenderId: '607004529726',
    projectId: 'cinemora-63661',
    storageBucket: 'cinemora-63661.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiKQ_KHBnQMpmqTbWOQdh-XpHUokF36OI',
    appId: '1:607004529726:ios:7a35fbe4b34d7875efed6f',
    messagingSenderId: '607004529726',
    projectId: 'cinemora-63661',
    storageBucket: 'cinemora-63661.firebasestorage.app',
    iosBundleId: 'com.example.cinemora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiKQ_KHBnQMpmqTbWOQdh-XpHUokF36OI',
    appId: '1:607004529726:ios:7a35fbe4b34d7875efed6f',
    messagingSenderId: '607004529726',
    projectId: 'cinemora-63661',
    storageBucket: 'cinemora-63661.firebasestorage.app',
    iosBundleId: 'com.example.cinemora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzDr_XflAEIQuTEiMSgqhEPXrWwCW7tPg',
    appId: '1:607004529726:web:50034da26264391fefed6f',
    messagingSenderId: '607004529726',
    projectId: 'cinemora-63661',
    authDomain: 'cinemora-63661.firebaseapp.com',
    storageBucket: 'cinemora-63661.firebasestorage.app',
    measurementId: 'G-C6Z0X6ZWP0',
  );
}
